### ISSUE TITLE
HexBytes nested in a dict[str, Any] have serialization problems

### ISSUE THREAD

**Issue by fubuloubu** [ApeWorX/eth-pydantic-types#14]
https://github.com/ApeWorX/eth-pydantic-types/blob/bf80c174cb2057d0587f7c7f3085b4d0b71dc530/eth_pydantic_types/hex.py#L43

**Comment by fubuloubu** [comment]
Might have to do with https://github.com/ApeWorX/eth-pydantic-types/blob/bf80c174cb2057d0587f7c7f3085b4d0b71dc530/eth_pydantic_types/hex.py#L50

**Comment by fubuloubu** [comment]
```py
(Pdb) event.model_dump()
{'event_name': 'StreamCreated', 'contract_address': '0x7B25175142886e34543247f4583fe034eafDee32', 'event_arguments': {'stream_id': 3, 'owner': '0x1C277bD41A276F87D3E92bccD50c7364aa2FFc69', 'token': '0xca24817BE6bCa07c9821E5f332a3F067158d6813', 'funded_amount': 1000000000000000000, 'time_left': 12933, 'products': [HexBytes('0x030000050300000100000000000000002f162ca27efe024edaa7cf0cc73fc7bd')]}, 'transaction_hash': '0xa4e7e4b64fd432e49cb1980f2762bc09b0f32a4ffe11cc3dddb29c6c24fbc9cf', 'block_number': 6803400, 'block_hash': '0x2c5997527bacb8c9dfa545adb77753d4fc433f9f47cad1d4e97ff6c0e5f22102', 'log_index': 1, 'transaction_index': 0}
(Pdb) event.model_dump_json()
*** UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa2 in position 19: invalid utf-8
```

**Comment by antazoey** [comment]
Okay the type looks like "`dict[str, Any]` where Any may be a list of HexBytes

**Comment by antazoey** [comment]
So this is not actually a bug. Ape is annotating with Any and the pydantic types don't run validators or serializers unless you annotate with those types. The fix is for Ape to add custom serializers for the Any type fields directly, which is what the attahed PR does.
